version: "3.1"
services:

    karate-db:
      image: mariadb:10.4
      container_name: karate-db
      restart: always
      working_dir: /application
      volumes:
        - /var/www/storage/database/karate/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=karate
        - MYSQL_USER=karate
        - MYSQL_PASSWORD=123456
        - TZ=America/Sao_Paulo
      ports:
        - "8095:3306"
